name: dbt_bc_project
version: "1.0.0"
config-version: 2

profile: fabric_warehouse

model-paths: ["models"]
test-paths:  ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_bc_project:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table

vars:
  source_schema: bronze
